{% set name = "abi-compliance-checker" %}
{% set version = "2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lvc/abi-compliance-checker/archive/refs/tags/{{ version }}.tar.gz
  sha256: b1e32a484211ec05d7f265ab4d2c1c52dcdb610708cb3f74d8aaeb7fe9685d64

build:
  number: 0
  skip: true  # [not linux]
  script:
    - sed -i "s|#!/usr/bin/perl|#!$PREFIX/bin/perl|" abi-compliance-checker.pl
    - make install prefix=$PREFIX

requirements:
  build:
    - make
  host:
    - perl >=5
  run:
    - {{ compiler('cxx') }}
    - abi-dumper >=1.1
    - binutils
    - perl >=5
    - universal-ctags

test:
  commands:
    - abi-compliance-checker --help

about:
  home: https://lvc.github.io/abi-compliance-checker/
  summary: 'A tool for checking backward API/ABI compatibility of a C/C++ library'
  description: >
    ABI Compliance Checker (ABICC) is a tool for checking backward binary and
    source-level compatibility of a C/C++ library.

    The tool analyzes changes in API/ABI (ABI=API+compiler ABI) that may break
    binary compatibility and/or source compatibility: changes in calling stack,
    v-table changes, removed symbols, renamed fields, etc.

    The tool can create and compare ABI dumps for header files and shared
    objects of a library. The ABI dump for a library can also be created by the
    ABI Dumper tool if shared objects include debug-info.
  license: LGPL-2.1-or-later
  license_file: LICENSE
  dev_url: https://github.com/lvc/abi-compliance-checker

extra:
  recipe-maintainers:
    - carterbox
